### PR TITLE
ovirt - initial seeding to support ovirt

### PR DESCRIPTION
**Pull request by bbuckingham**
This PR primarily contains changes to seed data needed to support oVirt.

For this first pass, the puppet module is being seeded in to a Foreman puppet environment (production).  Changes will be coming (in a future PR) to utilize Katello content management for this puppet content; however, this was the quickest way to make this functionality available.

### CODE REVIEW

**Comment by pitr-ch** [comment]
I am fuzzy in the installer area, cc @ares: What approach would you recommend for fusor, what should we avoid doing?

**Comment by ares** [comment]
I think this PR is OK for now. Later I'd encourage using apipie bindings rather then foreman-api. We should have some working example in Foreman 1.8 installer.

**Comment by pitr-ch** [comment]
@ares thanks for looking.

**Comment by bbuckingham** [comment]
@pitr-ch, @ares,  Thanks for looking it over!

**Comment by pitr-ch** [comment]
Ack.

**Pull request merged**
