### PR TITLE
1365509 - disable all except satellite repos. 

### PR DESCRIPTION
**Pull request by jmrodri**
Disable all repos except for the ones defined in the Satellite documentation.

### CODE REVIEW

**Comment by jmrodri** [comment]
## TEST

You can build a test srpm and copy it to your ISO Sat VM. Install the asciidoc package and rebuild the rpm on the ISO VM. Install it and run through the installer.
- Build a test SRPM

```
tito build --test --srpm
```
- Copy to your ISO VM

```
scp /tmp/path/to/srpm/ root@192.168.155.10:/tmp/
```

On your ISO VM:
- Get asciidoc and source-highlight from build system:

```
wget http://download.eng.bos.redhat.com/brewroot/packages/asciidoc/8.6.8/5.el7/noarch/asciidoc-8.6.8-5.el7.noarch.rpm
wget http://download.eng.bos.redhat.com/brewroot/packages/source-highlight/3.1.6/6.el7/x86_64/source-highlight-3.1.6-6.el7.x86_64.rpm
```
- Install the above rpms:

```
yum install asciidoc-8.6.8-5.el7.noarch.rpm source-highlight-3.1.6-6.el7.x86_64.rpm
```
- Rebuild rpm

```
rpmbuild --rebuild /tmp/fusor-installer......srpm
```
- Upgrade the new rpm

```
rpm -e --nodeps fusor-installer
rpm -Uvh /root/rpmbuild/RPMS/noarch/fusor-installer....rpm
```
- Run new installer

```
launch-fusor-installer
```

**Comment by djwhatle** [comment]
@jmrodri I'll test this today.

**Comment by jmrodri** [comment]
Also run `yum repolist` before and after so you can see the changes. 
https://bugzilla.redhat.com/show_bug.cgi?id=1365509#c12

**Comment by djwhatle** [comment]
ACK

```
[root@sat62fusor ~]# yum repolist
Loaded plugins: langpacks, product-id, search-disabled-repos, subscription-manager
repo id                                            repo name                                                                          status
rhel-7-server-rpms/7Server/x86_64                  Red Hat Enterprise Linux 7 Server (RPMs)                                           11,241
rhel-7-server-satellite-6.2-rpms/x86_64            Red Hat Satellite 6.2 (for RHEL 7 Server) (RPMs)                                      350
rhel-server-rhscl-7-rpms/7Server/x86_64            Red Hat Software Collections RPMs for Red Hat Enterprise Linux 7 Server             6,279
repolist: 17,870
[root@sat62fusor ~]#
```

Important parts...

```
Red Hat Enterprise Linux 7 Server (RPMs)
Red Hat Satellite 6.2 (for RHEL 7 Server) (RPMs)
Red Hat Software Collections RPMs for Red Hat Enterprise Linux 7 Server
```

**Pull request merged**
