### PR TITLE
1369434 - prompt change based on removal of  "do not configure networking"

### PR DESCRIPTION
**Pull request by djwhatle**
Change text in fusor-installer prompt for BZ 1369643.
`"select the option 'Do not configure networking' from the list below"`
to
`"select 'Configure networking' and change the value to false"`

### CODE REVIEW

**Comment by jmrodri** [comment]
The bug suggested we change the text not remove it:

```
The 'Do not configure networking' is not available in the list. Suggest changing it to:
---
If you DO NOT want to configure networking, select 'Configure networking' and change the value to false.
---
```

If we decided to remove it, comment on the bug that the solution was to remove the text vs rewording.

**Comment by jmrodri** [comment]
CONDACK pending outcome of whether we are to rephrase the text or remove it.

**Comment by djwhatle** [comment]
@jmrodri amended commit.

**Comment by jmrodri** [comment]
ACK

**Pull request merged**
