### PR TITLE
fusor-installer --reset needs to clear puppet environments too

### PR DESCRIPTION
**Pull request by sdherr**
This change enables us to reset a fusor installation with the --reset option.

### CODE REVIEW

**Comment by bbuckingham** [comment]
@sdherr, In order to make sure --reset works, please be sure to test the following scenario:
1. run installer
2. perform a deployment
3. run installer with --reset
4. perform another deployment

In the process, ensure that there are not errors reported along the way (e.g. in installer or as part of the deployment).  I began this task previously and observed some errors; however, perhaps they no longer exist.  Refer to the following PR for details: https://github.com/fusor/fusor-installer/pull/10 .  The PR was never merged as I wanted to go through the above flow again.

**Comment by sdherr** [comment]
@bbuckingham Yes, I've already done that. The deployments failed, but only because of Sat 6 sync problems, nothing to do with RHCI data. We can wait to merge until Sat 6 is no longer blocking us from doing any sort of successful testing, if you prefer.

**Comment by bbuckingham** [comment]
@sdherr, No worries, we can merge this in prior; however, I probably wouldn't mark the task complete until we can confirm that the full end-to-end scenario is functional.  It was quite a long time ago when I started working on changes to ensure support for --reset and re-running of the installer; however, I saw other issues during the provisioning phase (from the PR referenced, looks like the issues were related to Locations).  It is possible that those issues may no longer exist with the latest RHCI and Sat6; however, I want to be sure.

**Comment by jwmatthews** [comment]
ACK

**Pull request merged**
