### PR TITLE
Installer updates related to seeding

### PR DESCRIPTION
**Pull request by bbuckingham**
This PR contains a few commits for changes around the seeding performed by the installer.  The following is the high-level; however, refer to commits for more details:
1. address issues observed running --reset option
2. address issues observed when re-running installer after a deployment was performed
3. disable assignment of location to objects seeded

### CODE REVIEW

**Comment by bbuckingham** [comment]
Do not merge this PR, yet.  Observed an issue during testing and need to investigate if it is related.

**Comment by jwmatthews** [comment]
@bbuckingham should we consider merging this in?

**Comment by bbuckingham** [comment]
@jwmatthews, we need to hold off until we can test it out more.  Need to test an install, perform a deployment, re-run with --reset to ensure that it runs successfully, perform a deployment and ensure that all steps behave as expected.  I haven't had an opportunity to run through that test, with current tasks; however, it is on my list of things todo.  My concern is ensuring that the removal of 'location' doesn't impact the deployment or cleanup.

**Comment by bbuckingham** [comment]
The following PR was opened later to address the --reset option:
https://github.com/fusor/fusor-installer/pull/27; therefore, I am going to close this one out.  We can later open a new PR if any of these changes are needed.

**Pull request closed without merging**
