### PR TITLE
Addresses BZ 1197861

### PR DESCRIPTION
**Pull request by johnkim76**
https://bugzilla.redhat.com/show_bug.cgi?id=1197861

### CODE REVIEW

**Comment by johnkim76** [comment]
Screen shot of before and after.
bzbefore_white
bzafter_white

**Comment by jmrodri** [comment]
in the future make the commit message be bz# -  message. 1197861 - change color of 'proceed' prompt 

it makes it easier when we tag and build rpms

**Comment by johnkim76** [comment]
thank you, understood.

**Comment by jwmatthews** [comment]
@johnkim76 please put the 'green' color back on:
1. Proceed with the values shown

After that, this looks good and we can merge.

**Comment by johnkim76** [comment]
fixwhite_after

**Pull request merged**
